global:
  smtp_from: lab.alert.manager@gmail.com
  smtp_smarthost: smtp.gmail.com:587
  smtp_auth_username: lab.alert.manager@gmail.com
  smtp_auth_password: 3ringg_pass


route:
  group_by: [Alertname]
  receiver: email
  group_interval: 10s

receivers:
  - name: email
    email_configs:
    - to: "asafblevy@gmail.com"
    - to: "mord236@gmail.com"
