global:
  smtp_from: 1
  smtp_smarthost: smtp.gmail.com:587
  smtp_auth_username: 1
  smtp_auth_password: 2


route:
  group_by: [Alertname]
  receiver: email
  group_interval: 10s

receivers:
  - name: email
    email_configs:
    - to: "3"
    - to: "4"
    - to: "5"
