version: "3"
services:
  web1:
    image: nginx:latest
    environment:
      - NGINX_PORT=80
    networks:
      - backend
    volumes:
      - "./web1/index.html:/usr/share/nginx/html/index.html"
  web2:
    image: nginx:latest
    environment:
      - NGINX_PORT=80
    networks:
      - backend
    volumes:
      - "./web2/index.html:/usr/share/nginx/html/index.html"
  haproxy:
    image: haproxy:latest
    volumes:
      - "./haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg"
    ports:
      - "8081:80"
    networks:
      - backend
  prometheus:
    image: prom/prometheus
    volumes:
      - "./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml"
      - "./prometheus/alert_rules.yml:/etc/prometheus/alerts/alert_rules.yml"
    ports:
      - "9090:9090"
    networks:
      - backend
  cadvisor:
    image: gcr.io/google-containers/cadvisor:latest
    container_name: cadvisor
    ports:
    - "8080:8080"
    volumes:
    - "/:/rootfs:ro"
    - "/var/run:/var/run:rw"
    - "/sys:/sys:ro"
    - "/var/lib/docker/:/var/lib/docker:ro"
    networks:
      - backend
networks:
  backend:
    driver: bridge
